### ISSUE TITLE
cmake: allow building of static and dynamic libs at the same time

### ISSUE THREAD

**Issue by chadrik** [openexr/openexr#123]
Hi,
I just tried out the cmake build and I noticed that you have to build twice if you want both static and dymaic libs: once with `-DBUILD_SHARED_LIBS:BOOL=TRUE` and once with `-DBUILD_SHARED_LIBS:BOOL=FALSE`.  The old method using make would build both at the same time by default, and the ilmbase cmake scripts support this as well. It would be great if openexr could work the same way.

Thanks!

**Comment by kdt3rd** [comment]
This is in the new cmake setup. If you do cmake -DBUILD_SHARED_LIBS=ON -DILMBASE_BUILD_BOTH_STATIC_SHARED=ON -DOPENEXR_BUILD_BOTH_STATIC_SHARED=ON <whatever other options> path/to/src, you should then get both library types, and with the config mechanism generating imported libs, you can easily target either one. there are various settings controlling the naming of the libraries in the *Setup.cmake files in each respective config folder
