### ISSUE TITLE
IlmImf Thread should report an 'optimal' number ofthreads to use.

### ISSUE THREAD

**Issue by pstanczyk** [openexr/openexr#15]
One thing regarding threads and the IlmThread::ThreadPool. It would be useful with a, Imf::idealThreadCount() to query for the ideal number of threads for your current architecture. This is probably not need when running OpenEXR from a renderer or more complex application but extremely useful when running pipeline utilities with "OpenEXR-only" linked.
Not sure though how much it relates to OpenEXR but if the platform specific code is in place it would really be superb.

Mikael

**Comment by cary-ilm** [comment]
Looking into the OpenEXR issue backlog. @kdt3rd, did your reworking of IlmThread address this? Is this worth keeping as an open issue?

**Comment by kdt3rd** [comment]
w/ c++11, the need for this is reduced, as people can just use std::thread::hardware_concurrency. However, a good point was raised that if core count changes or memory architectures change, we may want to not just return the number of cores. As such, added a (static) ThreadPool::estimateThreadCountForFileIO(). If someone else is just using threadpool for it's abilities, they can do what they want, and probably should anyway if their host is any sort of reasonably complex.
