### ISSUE TITLE
build issue, debian 7.0 x64

### ISSUE THREAD

**Issue by unicomp21** [openexr/openexr#150]
After doing bootstrap, configure, make, make install for Ilmbase, can't build openexr

checking for IlmBase... no
**\* Could not run the IlmBase test program, checking why...
**\* The test program compiled and staticly linked, but did not run. This
**\* usually means that the run-time linker is not finding IlmBase or finding
**\* the wrong version of IlmBase.

---

**\* If the linker is not finding IlmBase, you'll need to set your
**\* LD_LIBRARY_PATH environment variable, or edit /etc/ld.so.conf to point
**\* to the installed location  Also, make sure you have run ldconfig if that
**\* is required on your system.

---

**\* Flags used by the test:
**\*     cflags: -g -O2  -I/usr/local/include/OpenEXR -pthread
**\*     ldflags:   -L/usr/local/lib

---

**\* You can also run configure with --disable-ilmbasetest to skip this test.
configure: error: Could not compile IlmBase test program.

**Comment by meshula** [comment]
Dumb question, have all of build systems for all of the test programs, viewers, etc., been updated to reference the 2.2 suffixed .so names?

**Comment by unicomp21** [comment]
+oiio

**Comment by unicomp21** [comment]
fyi, OpenShadingLanguage depends on OpenImageIO/oiio, which depends on OpenEXR.  I'm experiencing considerable difficulty getting everything to build on Linux.

**Comment by meshula** [comment]
https://github.com/openexr/openexr/issues/130
https://github.com/tota/freebsd-ports/commit/4d60094be2c5dbadc63ec7b91e8822a90e7a3182
https://github.com/openexr/openexr/pull/149#issuecomment-68301480
https://groups.google.com/forum/#!topic/alembic-discussion/WrK6dTOfFj8

**Comment by cary-ilm** [comment]
Looking into the OpenEXR issue backlog.  Was there ever a resolution of this?

**Comment by meshula** [comment]
Paging @lgritz —- pretty sure there are no issues around the OpenEXR, OSL, OIIO combo these days?

**Comment by lgritz** [comment]
Not sure what the issues were back in 2015, but we certainly don't have any trouble building these things now. I assume long since fixed. I would recommend closing this issue and people will re-file if there are continuing troubles.
