### ISSUE TITLE
DWA decompressor bug

### ISSUE THREAD

**Issue by liangck** [openexr/openexr#161]
DwaCompressor::LossyDctDecoderBase::execute uses different inverse DCT according to the number of non-zero coefficients. However, it seems the implementation is inexact and would not match the results of using dctInverse8x8_0 for all cases.

It is more obvious when dwaCompressionLevel is set to a high value. The example below is obtained by dwaCompressionLevel=2500.
<img width="1436" alt="left_adaptive_right_fixed" src="https://cloud.githubusercontent.com/assets/911539/8846012/804d34ae-30d8-11e5-9db5-ec29561a6299.png">

The left is the current implementation, and the right is the result if I comment out all dctInverse8x8_i and use dctInverse8x8_0 for all blocks. It is much slower so not an ideal solution.

**Comment by liangck** [comment]
Add @karlrasche

**Comment by karlrasche** [comment]
By any chance is this resolved by #143?

-Karl

**Comment by liangck** [comment]
Works! Thanks.

**Comment by karlrasche** [comment]
Good deal
