### ISSUE TITLE
Problems building the OpenEXR-2.2.0

### ISSUE THREAD

**Issue by frmsaul** [openexr/openexr#163]
Hi, 

Im trying to build OpenEXR on my machine (Ubuntu 14.0 64 bit) and facing some errors.
When I run the `configure` script in the `openexr-2.2.0` folder, I get the following error:

```
checking for IlmBase... no
*** Could not run the IlmBase test program, checking why...
*** The test program compiled and staticly linked, but did not run. This 
*** usually means that the run-time linker is not finding IlmBase or finding
*** the wrong version of IlmBase.
***
*** If the linker is not finding IlmBase, you'll need to set your
*** LD_LIBRARY_PATH environment variable, or edit /etc/ld.so.conf to point
*** to the installed location  Also, make sure you have run ldconfig if that
*** is required on your system.
***
*** Flags used by the test:
***     cflags: -g -O2 -pthread -I/usr/local/include/OpenEXR   
***     ldflags:  -L/usr/local/lib  
***
*** You can also run configure with --disable-ilmbasetest to skip this test.
configure: error: Could not compile IlmBase test program.
```

Any idea what might be causing it?

P.S, 

I successfully build `ilmbase-2.2.0`, but when I try `sudo make install` in the `ilmbase-2.2.0` folder, I get the following error:

```
mv: cannot stat 'libIlmThread-2_2.so.12.0.0': No such file or directory
libtool: install: error: relink `libIlmThread.la' with the above command before installing it
make[2]: *** [install-libLTLIBRARIES] Error 1
make[2]: Leaving directory `/home/frmsaul/***/***/***/OpenEXR/ilmbase-2.2.0/IlmThread'
make[1]: *** [install-am] Error 2
make[1]: Leaving directory `/home/frmsaul/***/***/***/ilmbase-2.2.0/IlmThread'
make: *** [install-recursive] Error 1
```

How do I resolve the issue?

Thanks, 

Saul

**Comment by karlrasche** [comment]
The first error is usually related to not being able to locate the IlmBase libs. If you check the config.log file, you should be able to find the compiler output for the failed test (amongst lots of other stuff). 

Given that you're also seeing some sort of IlmBase link problem in the second error, its quite possible the two are related.

**Comment by cary-ilm** [comment]
Looking into the OpenEXR issue backlog.  Is this still an open issue?

**Comment by kdt3rd** [comment]
we are largely shifting to using cmake as the primary build mechanism, which now uses the modern cmake of exporting cmake configs which should be able to be auto-discovered if they are installed in the standard places (or you can set the cmake search path if you are installing in a non-standard location). Please let us know if there are any build issues with this path.
