### ISSUE TITLE
Windows compilation with openexr v2.2.0

### ISSUE THREAD

**Issue by hevy-CC4477** [openexr/openexr#169]
Hi,

I am stuck with link errors during the compilation of openexr  on windows with visual studio 2013:
- unresolved external symbol compress2 referenced in function ...
- unresolved external symbol uncompress referenced in function ...

I am compiling with zlib-v1.2.8 and ilmbase v2.2.0. Does some one know how to fix this issue ?

Thanks,

**Comment by meshula** [comment]
That usually happens if you haven't set up the ZDLL preprocessor definition consistently between all three of OpenEXR, zlib, and your app, -or- if you have not actually linked the zlib library, -or- if there is another copy of the zlib library in your search path that breaks the prepocessor definition set up.

**Comment by hevy-CC4477** [comment]
You are almost good. The error did not come from openexr but zlib. They forgot to add the definition of ZLIB_WINAPI in their CMakeLists.txt when you compile under windows. I will shortly do a pull request to zlib to fix that.

**Comment by meshula** [comment]
Glad you found it, and that I was on the right track, it's been a little while since I had to debug zlib problems on Windows :)

**Comment by hevy-CC4477** [comment]
By the way I did a pull request for openexr and the windows compilation if you could take a look (https://github.com/openexr/openexr/pull/171).

**Comment by sandeepvr40** [comment]
@hevy-CC4477 error LNK2019 compress2, compressBound and uncompressed persists even after using fix mentioned in #116. I am compiling using Zlib 1.2.11. 
Any idea what could be still going wrong?
