### ISSUE TITLE
Implement a canonical FindIlmbase.cmake

### ISSUE THREAD

**Issue by pstanczyk** [openexr/openexr#176]
Seems there are countless implementations of FindIlmbase.cmake, some better than others 
https://www.google.com/#q=FindIlmbase.cmake

It would be great if the OpenEXR distribution could provide a good one.

**Comment by kdt3rd** [comment]
This has been replaced by the canonical "config" / export system built into cmake. It should place files automatically into <installroot>/lib/cmake/_package_/_package_.cmake
