### ISSUE TITLE
PyIlmBase Cmake unable to find Boost

### ISSUE THREAD

**Issue by bfloch** [openexr/openexr#191]
We're on linux here and for us all are boost packages are lowercase (without us manually overriding it).

Whatever we do with the current CMakeLists.txt of PyIlmBase FindBoost can not find libboost_python.
`-DBoost_DEBUG=ON` reveals that it does find the inlcudes, library paths etc. but fails finding the specific component.

Before submitting a pull request I wonder if there is a reason for the current spelling (windows?)

This fixes it for us:

```
--- CMakeLists.txt  2014-08-10 00:21:45.000000000 -0400
+++ CMakeLists.txt.fixed    2016-05-17 10:24:47.555378446 -0400
@@ -39,7 +39,7 @@
 FIND_PACKAGE ( PythonLibs REQUIRED )
 FIND_PACKAGE ( PythonInterp REQUIRED )
 FIND_PACKAGE ( Boost
-   COMPONENTS Python
+   COMPONENTS python
 )
```

**Comment by kdt3rd** [comment]
This has been resolved in the new cmake refactor, do note that the next release we will require cmake 3.12 to get the new FindPython goodness. Thanks!
