### ISSUE TITLE
Unexpected rpaths on macOS

### ISSUE THREAD

**Issue by meshula** [openexr/openexr#199]
See some samples below. Cmake generates dylibs with a 0.0, and symlinks to versions without the 0.0. Is it expected that the rpaths point to symlinks instead of the library itself? Is the reasoning that iterations at the 12.x.y level are irrelevant, so we can keep building OpenExr minor versions but don't need to relink dependencies since the rpath will resolve through a symlink?

local/lib/libHalf.12.0.0.dylib:
         name @rpath/libHalf.12.dylib (offset 24)

local/lib/libIex-2_2.12.0.0.dylib:
         name @rpath/libIex-2_2.12.dylib (offset 24)

otool -l local/lib/libIlmImf-2_2.22.0.0.dylib|grep dylib                                                     ~/Projects/usd2/stage
local/lib/libIlmImf-2_2.22.0.0.dylib:
         name @rpath/libIlmImf-2_2.22.dylib (offset 24)
         name @rpath/libHalf.12.dylib (offset 24)
         name @rpath/libIex-2_2.12.dylib (offset 24)
         name @rpath/libImath-2_2.12.dylib (offset 24)
         name @rpath/libIlmThread-2_2.12.dylib (offset 24)

**Comment by kdt3rd** [comment]
Closing old ticket...

All of the library names should now be centralized in the newly refactored cmake coming in the next release. The so version (22.0.0) [as different from the library version] should indicate the abi present, and so yes, does not require the minor / patch releases in there, until we were to do such a release, which I don't think we've done yet :)
