### ISSUE TITLE
Id like to propose a fast low complexity HDR lossless compression algorithm

### ISSUE THREAD

**Issue by conradgaunt** [openexr/openexr#212]
hello openexr people,

 i don't have an issue with openexr, however..

 i do have a patent free, low complexity lossless compression algorithm that outperforms Piz in terms of compression ratios, and like Piz has near symmetrical encoding/ decoding ( despite my terrible programming ) . implementation would be trivial

if anyone here is interested in taking a look at it / evaluating it for use in openexr , id be happy to share it with them . it is not optimised for speed (I'm not that sort of programmer)

I'm writing this message .. as direct contact isn't easy on GitHub

k.r

**Comment by ehanway-ilm** [comment]
I can't make a guarantee that we'll accept it into OpenEXR, but there are a few options you can take to further the discussion...

- If you have code, you can submit a pull request.
- For public discussion, you can use the openexr-devel mailing list (subscription info can be found via openexr.com).
- For private follow-up, you can form my email from my github userid by substituting the '-' with a '@' and appending '.com'.

**Comment by ehanway-ilm** [comment]
Closing issue.  Will follow up on mailing list.
