### ISSUE TITLE
Reading OpenCV generated exr image causes "Cannot handle YCA image now!" error

### ISSUE THREAD

**Issue by jasjuang** [openexr/openexr#214]
I am able to use exrdisplay to read images from https://github.com/openexr/openexr-images, so I believe I build openexr correctly. However, I am having trouble to read the exr images generated by OpenCV. The OpenCV code that I used to generate exr image is

``````
cv::Mat test = cv::Mat(480, 640, CV_32FC1, cv::Scalar(1.1f));
cv::imwrite("test.png", test);
``````

It's a single channel image with all value 1.1f, but when I attempt to load it with exrdisplay

``````
./exrdisplay test.png
``````

I get an error message

``````
Cannot handle YCA image now!
Warning: Environment variable CTL_DISPLAY_CHROMATICITIES is not set; using default value (chromaticities according to Rec. ITU-R BT.709).
Warning: Environment variable EXR_DISPLAY_VIDEO_GAMMA is not set; using default value (2.2).
``````

and there is nothing shown in the image. 

But the weird thing is if I do sudo apt-get install openexr-viewers instead of building from source. I am actually able to read the exr image successfully. Is it possible that some of the new commits breaks something?

**Comment by ehanway-ilm** [comment]
Looks like this has always been the behavior of exrdisplay.  If no channel name is passed on the command line, it will assume it's trying to display RGB and when it encounters a channel named Y, you'll run into this case.  You can use it to display the file by running 'exrdisplay -c Y yourfile.exr'

**Comment by jasjuang** [comment]
Thanks, the `-c Y` flag solves it for me
