### ISSUE TITLE
ilmbase: Proprietary licence in halfExport.h

### ISSUE THREAD

**Issue by malaterre** [openexr/openexr#219]
There is something clearly wrong with the license associated with this file:

* https://github.com/openexr/openexr/blob/develop/IlmBase/Half/halfExport.h

> //
> //  Copyright (c) 2008 Lucasfilm Entertainment Company Ltd.
> //  All rights reserved.   Used under authorization.
> //  This material contains the confidential and proprietary
> //  information of Lucasfilm Entertainment Company and
> //  may not be copied in whole or in part without the express
> //  written permission of Lucasfilm Entertainment Company.
> //  This copyright notice does not imply publication.
> //

Could you please fix this license ASAP, this is a serious issue for distribution like Debian. Thanks.

**Comment by malaterre** [comment]
Original report here: https://bugs.debian.org/843594

**Comment by ehanway-ilm** [comment]
Sorry, that's just an oversight.  We'll get it replaced with the appropriate license consistent with the rest of the package ASAP.

For Debian, is it sufficient for the fix to be at the head of the develop branch, or does it need to be in a numbered release?

**Comment by ehanway-ilm** [comment]
License corrected in development branch now.

**Comment by malaterre** [comment]
Great ! I see the patch here:

* https://github.com/openexr/openexr/commit/20d043d017d4b752356bb76946ffdffaa9c15c72

That's enough for us within Debian, no need for a new version release. Thanks for the quick update.

**Comment by malaterre** [comment]
@cary-ilm Thanks for preparing v2.2.1 release. We are going to use this new release in Debian. However would you please apply git commit 20d043d to your release branch. That would be wonderful, otherwise @mfvescovi will need to integrate -again- a local patch in Debian.

**Comment by malaterre** [comment]
Could some kind repo collaborator re-open the issue to keep track of it progress ? Debian BTS can watch automatically the status of github bug tracker.
