### ISSUE TITLE
IMathExc - multiple definitions on linking.

### ISSUE THREAD

**Issue by SimonCSmith** [openexr/openexr#226]
I am seeing this issue under Window, Visual Studio 2015. I've not tested this under OSX or Linux.

If you have 2 project libraries in your solution and include (and use) ImathMatrix in both libraries, when it comes to linking you will get a "mutiply defined symbol found" error for the thrown exceptions.

`Imath-2_2.lib(Imath-2_2.dll) : error LNK2005: "public: __cdecl Imath_2_2::SingMatrixExc::SingMatrixExc(char const *)" (??0SingMatrixExc@Imath_2_2@@QEAA@PEBD@Z) already defined in xxxx.lib(xxxx.obj). fatal error LNK1169: one or more multiply defined symbols found.
`

I believe this is due to the macros that define the classes on the fly creating identical classes (and implementation) in separate libraries, so upon linking the linker complains or just gets confused. 

The use case is simple.
1) Include ImathMatrix.h in one project and call inverse on a matrix instance in your cpp file.
2) Repeat step 1 for another project in the same solution.
3) Ensure the solution uses and links to both projects.
4) Build solution and note the linker error.

The only (temporary) solution for me at the moment is to comment out all the throw calls in the headers. Whilst that is fine by me (we always call with singExc as false) one assumes that this would occur for any other parts of the library that use this way of defining the exception macros.

Comments, suggestions, workarounds, and fixes welcome!

Cheers,
   Simon.

**Comment by meshula** [comment]
Have you defined OPENEXR_DLL in your own project that calls OpenEXR? If you don't, functions will get inlined into your own libraries and cause a conflict.

**Comment by meshula** [comment]
Recent changes to the build system should have addressed confusion or issues around shared/static library linking. If there's still a problem please reopen.
