### ISSUE TITLE
Imf::OutputFile Produce binary different files

### ISSUE THREAD

**Issue by haotj** [openexr/openexr#230]
I use both
OutputFile (const char fileName[], const Header &header, int numThreads = globalThreadCount());
OutputFile (OPENEXR_IMF_INTERNAL_NAMESPACE::OStream &os, const Header &header, int numThreads = globalThreadCount());

I have a implemented pure virtual functions of OStream with a big buffer(memset to 0). Once it's finished, I write the buffer to disk which produces identical image to the const char* fileName[] version. However, when I tried to do a binary diff, I see from 0x00000130 to 0x0000230, they are different.
![diff](https://cloud.githubusercontent.com/assets/24230303/25254101/af859314-25d8-11e7-8d53-3dbe67282d58.jpg)

Now, both images "look" the same, and have same pixel values, I'm not sure why the data is different. The output file using the fileName ctor, actually produces identical binaries, so I don't think it's caused by un-initialized memory.

**Comment by oleksiivorobiov** [comment]
Make sure you dump file on disk after OutputFile destructor call. It writes this values inside destructor

**Comment by cary-ilm** [comment]
Looking into the OpenEXR issue backlog. Is this still an issue? Does the suggestion resolve it?

**Comment by cary-ilm** [comment]
Closing the issue for now, feel free to re-open or file a new issue if you need further help.
