### ISSUE TITLE
C++17 Deprecated dynamic exception specifications in OpenEXR

### ISSUE THREAD

**Issue by tomansill** [openexr/openexr#235]
Hi, I was using OpenImageIO library that uses OpenEXR as a dependency. I tried to compile my project that uses OpenImageIO which includes some stuff in OpenEXR and it has failed to compile. 

The compilation error log shows: 
https://gist.github.com/tomansill/02a278d8cba469b9fb7c67a9f664a23d

I was compiling with GCC 8 and used C++17 specification. I am running on Arch Linux and I used OpenEXR from Arch Linux's repo. 

I looked up on this issue, and I found this: 
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0003r0.html

It appears that C++17 has deprecated dynamic exception specifications and disallows it when I try to compile it. 

It seemed to me that the solution to this issue is to simply remove the clause `throw (IEX_NAMESPACE::*Exc)` in both header and implementation files. I have tested it on my own other projects, by reproducing the error by including the specification and compiling it with C++14 then it will produce error with C++17 and removing the specification will make the compilation process to be successful.

**Comment by tomansill** [comment]
Ok, I edited the files 

- ilmBase/imath/imathMatrix.h
- ilmBase/imath/imathVec.cpp
- ilmBase/imath/imathVec.h

to remove all throw(IEX_NAMESPACE::MathExc) and tried to compile it with c++17, the errors went away.

I also have to fix the following:

- OpenEXR/exrmakepreview/makePreview.cpp
- OpenEXR/exrmaketiled/makeTiled.cpp
- OpenEXR/ilmimfExamples/previewImageExamples.cpp

because those files use the "clamp" function which is supposed to refer to clamp function in imathFun.h.  However, the files listed above, uses both namespace std and IMATH_NAMESPACE and it appears that c++17 has introduced a new function called "clamp" and it caused compilation errors due to ambiguous functions in IMATH_NAMESPACE and std namespaces. I fixed the problem by adding IMATH_NAMESPACE:: to every clamp function. 

Both ilmBase and OpenEXR compiles successfully. Then I tried to compile it with my project and it also compiles successfully.

**Comment by robpieke** [comment]
Putting on the radar of @lgritz as there's a recent similar discussion on openexr-devel

**Comment by lgritz** [comment]
Without having previously seen this PR (sorry), I also independently submitted a patch that addresses the dynamic exception issue: #243. Like this one, it's been waiting for many weeks to get reviewed, merged, and have a new official release made. 

I'm sure there are many other gems/necessities festering in the pile of unmerged PRs for the OpenEXR project.

**Comment by meshula** [comment]
Resolved in https://github.com/openexr/openexr/pull/280

**Comment by martin-ejdestig** [comment]
When can a release be made with fixes for this in it?

Both GCC (8.1) and Clang (6.0) are released now and have pretty good C++17 support, which means this will be problematic for more people. (Personally I will probably disable use of OpenEXR in my projects until this is fixed.)
