### ISSUE TITLE
pyilmbase error vs2015 with boost1.61 and python27 please help ，alse error

### ISSUE THREAD

**Issue by ArthurChiu** [openexr/openexr#239]
error LNK2019: unresolved external symbol "class boost::python::class_&amp;amp;lt;class Imath_2_2::Rand32,struct boost::python::detail::not_specified,struct boost::python::detail::not_specified,struct boost::python::detail::not_specified> __cdecl PyImath::register_Rand32(void)" (?register_Rand32@PyImath@@YA?AV?$class_@VRand32@Imath_2_2@@Unot_specified@detail@python@boost@@U3456@U3456@@python@boost@@XZ) referenced in function "void __cdecl init_module_imath(void)" (?init_module_imath@@YAXXZ)4>imathmodule.obj : error LNK2019: unresolved external symbol "class boost::python::class_&amp;amp;lt;class Imath_2_2::Rand48,struct boost::python::detail::not_specified,struct boost::python::detail::not_specified,struct boost::python::detail::not_specified> __cdecl PyImath::register_Rand48(void)" (?register_Rand48@PyImath@@YA?AV?$class_@VRand48@Imath_2_2@@Unot_specified@detail@python@boost@@U3456@U3456@@python@boost@@XZ) referenced in function "void __cdecl init_module_imath(void)" (?init_module_imath@@YAXXZ)4>imathmodule.obj : error LNK2019: unresolved external symbol "void __cdecl PyImath::register_StringArrays(void)" (?register_StringArrays@PyImath@@YAXXZ) referenced in function "void __cdecl init_module_imath(void)" (?init_module_imath@@YAXXZ)4>PyImathFun.obj : error LNK2019: unresolved external symbol "public: __cdecl PyImath::PyReleaseLock::PyReleaseLock(void)" (??0PyReleaseLock@PyImath@@QEAA@XZ) referenced in function "public: static class PyImath::FixedArray&amp;amp;lt;int> __cdecl PyImath::detail::VectorizedFunction1&amp;amp;lt;struct PyImath::`anonymous namespace'::abs_op&amp;amp;lt;int>,struct boost::mpl::vector1&amp;amp;lt;struct boost::mpl::bool_&amp;amp;lt;1> >,int __cdecl(int)>::apply(class PyImath::FixedArray&amp;amp;lt;int> const &)" (?apply@?$VectorizedFunction1@U?$abs_op@H@?A0x72aaa1b5@PyImath@@U?$vector1@U?$bool_@$00@mpl@boost@@@mpl@boost@@$$A6AHH@Z@detail@PyImath@@SA?AV?$FixedArray@H@3@AEBV43@@Z)4>PyImathBasicTypes.obj : error LNK2001: unresolved external symbol "public: __cdecl PyImath::PyReleaseLock::PyReleaseLock(void)" (??0PyReleaseLock@PyImath@@QEAA@XZ)4>PyImathFun.obj : error LNK2019: unresolved external symbol "public: __cdecl PyImath::PyReleaseLock::~PyReleaseLock(void)" (??1PyReleaseLock@PyImath@@QEAA@XZ) referenced in function "public: static class PyImath::FixedArray&amp;amp;lt;int> __cdecl PyImath::detail::VectorizedFunction1&amp;amp;lt;struct PyImath::`anonymous namespace'::abs_op&amp;amp;lt;int>,struct boost::mpl::vector1&amp;amp;lt;struct boost::mpl::bool_&amp;amp;lt;1> >,int __cdecl(int)>::apply(class PyImath::FixedArray&amp;amp;lt;int> const &)" (?apply@?$VectorizedFunction1@U?$abs_op@H@?A0x72aaa1b5@PyImath@@U?$vector1@U?$bool_@$00@mpl@boost@@@mpl@boost@@$$A6AHH@Z@detail@PyImath@@SA?AV?$FixedArray@H@3@AEBV43@@Z)4>PyImathBasicTypes.obj : error LNK2001: unresolved external symbol "public: __cdecl PyImath::PyReleaseLock::~PyReleaseLock(void)" (??1PyReleaseLock@PyImath@@QEAA@XZ)4>PyImathFun.obj : error LNK2019: unresolved external symbol "void __cdecl PyImath::dispatchTask(struct PyImath::Task &,unsigned __int64)" (?dispatchTask@PyImath@@YAXAEAUTask@1@_K@Z) referenced in function "public: static class PyImath::FixedArray&amp;amp;lt;int> __cdecl PyImath::detail::VectorizedFunction1&amp;amp;lt;struct PyImath::`anonymous namespace'::abs_op&amp;amp;lt;int>,struct boost::mpl::vector1&amp;amp;lt;struct boost::mpl::bool_&amp;amp;lt;1> >,int __cdecl(int)>::apply(class PyImath::FixedArray&amp;amp;lt;int> const &)" (?apply@?$VectorizedFunction1@U?$abs_op@H@?A0x72aaa1b5@PyImath@@U?$vector1@U?$bool_@$00@mpl@boost@@@mpl@boost@@$$A6AHH@Z@detail@PyImath@@SA?AV?$FixedArray@H@3@AEBV43@@Z)4>PyImathBasicTypes.obj : error LNK2001: unresolved external symbol "void __cdecl PyImath::dispatchTask(struct PyImath::Task &,unsigned __int64)" (?dispatchTask@PyImath@@YAXAEAUTask@1@_K@Z)

**Comment by Arturo-gutierrez** [comment]
I am having the same error. The thing is that in  `PyImathExport.h` line 43:44 you have this:

`#    define PYIMATH_EXPORT_DEFINITION __declspec(dllexport) 
#    define PYIMATH_IMPORT_DEFINITION __declspec(dllimport)`

that at compile time it gives errors like this:

`LNK2019	unresolved external symbol "__declspec(dllimport) public: __cdecl boost::python::handle<struct _object>::handle<struct _object>(void)" (__imp_??0?$handle@U_object@@@python@boost@@QEAA@XZ) referenced in function "public: void __cdecl boost::python::detail::keyword::`default constructor closure'(void)" (??_Fkeyword@detail@python@boost@@QEAAXXZ)	imathnumpymodule	\pyilmbase-2.2.1\PyImathNumpy\imathnumpymodule.obj	1		
`


I am using VS2015 x64  with Boost_1_55_0

**Comment by meshula** [comment]
Note, this is the same issue as https://github.com/openexr/openexr/issues/162.

**Comment by meshula** [comment]
Linking issues resolved by 

https://github.com/openexr/openexr/commit/72c41f705df9c8efcaee8ee2ce3275620471de29

There may be runtime issues to be resolved before this can be merged to master.

**Comment by cary-ilm** [comment]
Looking into the OpenEXR issue backlog. This appears resolved as of v2.3.0, so closing.
