### ISSUE TITLE
Cannot write to Z channel

### ISSUE THREAD

**Issue by chaosink** [openexr/openexr#244]
I'm trying the read/write examples in the following official documentation:

[ReadingAndWritingImageFiles.pdf](http://www.openexr.com/ReadingAndWritingImageFiles.pdf), Page 10, "Writing an Image File"

But I can't write to the Z channel. The image is all black in exrdisplay(the official EXR viewer) even the exposure is max.

If I replace 'Z' with 'R' then I can see a reddish image using exrdisplay.

**Comment by cary-ilm** [comment]
Looking into the backlog of open OpenEXR issues. Is this still a problem?  Closing the issue for now, feel free to re-open or file a new issue if you need further help.
