### ISSUE TITLE
half.h default user-provided constructor breaks c++ semantics (value/zero initialization vs default initialization)

### ISSUE THREAD

**Issue by geotz** [openexr/openexr#246]
The user-provided default constructor for `half` in `half.h` does not respect value/zero initialization which makes the type awkward and/or buggy to work with, especially in generic template code that works with other number types (e.g. floats).

**Expected behavior (as with float):**
```
using T = float;
std::vector<T> a(5);	// initialized with 0’s
T b[5];			// uninitialized 
T c[5] = {};		// initialized with 0’s
T d;			// uninitialized
```
**Current behavior (half):**
```
using T = half;
std::vector<T> a(5);	// uninitialized
T b[5];			// uninitialized 
T c[5] = {}; 		// uninitialized
T d; 			// uninitialized
```
**Proposed solution (C++11)**
In class definition (`half.h`) define the default constructor as an _explicitly defaulted_ one:
```
class half
{
  public:

    //-------------
    // Constructors
    //-------------

    half () = default;
// ...
```
in order to correctly perform value initialization or default initialization (which actually does nothing). The `unsigned short` member's 0 value coincides with 16-bit floating point value 0. With the proposed solution, we have the same behavior as with floats.

**Comment by meshula** [comment]
This seems reasonable.

**Comment by milasudril** [comment]
I would be happy to see this fix merged soon. This will also make the following compile:

    static_assert(std::is_trivially_default_constructible_v<half>);
