### ISSUE TITLE
[VS 2015] Can't run tests and OpenVDB compile errors

### ISSUE THREAD

**Issue by omento** [openexr/openexr#254]
When building IlmBase and OpenEXR, everything works just fine, almost. I can build and test IlmBase with no issues. I can build OpenEXR, but I can't run tests (they fail after the first one).

[Pastebin of test failure](https://pastebin.com/fC42wLZR)

When using the library with OpenVDB to build the `openvdb_shared` target, I can't get past the following error: [Pastebin of compile error](https://pastebin.com/ezktv7Te)

All I've been able to find online are references to the flags "OPENEXR_DLL" and "HALF_EXPORT". This is my first attempt at building anything on Windows (got everything working fine on Linux) and I don't know how to implement these. Everything I've tried (standard CMake '-D' options, CMAKE_CXX_FLAGS as "-OPENEXR_DLL", etc). has not accomplished anything. I'm building as per the instruction in the `README.cmake.txt` file. Using VS 2017 with the 2015.3 (14.0) build tools.

Any help would be appreciated! I need to solve this error to get any further with the OpenVDB build.

**Comment by meshula** [comment]
What's your command line to build OpenVdb?

**Comment by omento** [comment]
@meshula 

```
setlocal
del /f CMakeCache.txt
set DEP_ROOT="C:\Code\vfx"
set BOOST_ROOT=%DEP_ROOT%\boost
set GLEW_ROOT=%DEP_ROOT%\glew\1.13.0
set GLFW3_ROOT=%DEP_ROOT%\glfw\3.2.1
set ILMBASE_ROOT=%DEP_ROOT%\openexr\2.2.1
set OPENEXR_ROOT=%DEP_ROOT%\openexr\2.2.1
set MAYA_LOCATION="C:\Program Files\Autodesk\Maya2018"
set TBB_ROOT=%MAYA_LOCATION%\lib
set BLOSC_ROOT=%DEP_ROOT%\c-blosc\1.7.0
set ZLIB_ROOT=%DEP_ROOT%\zlib\1.12.11
set CPPUNIT_ROOT=%DEP_ROOT%\cppunit\1.14.0
set VDB_INSTALL=%DEP_ROOT%\openvdb\4.0.2
cmake -Wdev ^
      -D Blosc_USE_STATIC_LIBS=ON ^
      -D BLOSC_LOCATION=%BLOSC_ROOT% ^
      -D USE_GLFW3=ON ^
      -D GLEW_LOCATION=%GLEW_ROOT% ^
      -D GLFW3_LOCATION=%GLFW3_ROOT% ^
      -D GLFW3_USE_STATIC_LIBS=ON ^
      -D Boost_USE_STATIC_LIBS=ON ^
      -D Boost_INCLUDE_DIR=%BOOST_ROOT% ^
      -D BOOST_LIBRARYDIR=%BOOST_ROOT%\lib64-msvc-14.0 ^
      -D ZLIB_INCLUDE_DIR=%ZLIB_ROOT%\include ^
      -D ZLIB_LIBRARY=%ZLIB_ROOT%\lib\zlibstatic.lib ^
      -D TBB_LOCATION=%TBB_ROOT% ^
      -D TBB_LIBRARYDIR=%TBB_ROOT% ^
      -D TBB_INCLUDE_DIR=%MAYA_LOCATION%\include ^
      -D Tbb_TBB_LIBRARY=%TBB_ROOT%\tbb.lib ^
      -D Tbb_TBBMALLOC_LIBRARY=%TBB_ROOT%\tbbmalloc.lib ^
      -D Tbb_TBB_PREVIEW_LIBRARY=%TBB_ROOT%\tbb_preview.lib ^
      -D ILMBASE_LOCATION=%ILMBASE_ROOT% ^
      -D ILMBASE_NAMESPACE_VERSIONING=ON ^
      -D Ilmbase_HALF_DLL=%ILMBASE_ROOT%\lib\Half.dll ^
      -D OPENEXR_LOCATION=%OPENEXR_ROOT% ^
      -D OPENEXR_NAMESPACE_VERSIONING=ON ^
      -D PYTHON_LIBRARY=%TBB_ROOT%\python27.lib ^
      -D PYTHON_INCLUDE_DIR=%MAYA_LOCATION%\include\python2.7 ^
      -D PYTHON_EXECUTABLE=%MAYA_LOCATION%\bin\mayapy.exe ^
      -D CPPUNIT_LOCATION=%CPPUNIT_ROOT% ^
      -D MAYA_LOCATION=%MAYA_LOCATION% ^
      -D OPENVDB_ENABLE_3_ABI_COMPATIBLE=ON ^
      -D OPENVDB_BUILD_MAYA_PLUGIN=ON ^
      -D OPENVDB_MAYA_INSTALL_MOD=ON ^
      -D OPENVDB_MAYA_SUBDIR=OFF ^
      -D OPENVDB_MAYA_INSTALL_BASE_DIR=%VDB_INSTALL%\maya2018 ^
      -D OPENVDB_BUILD_CORE=ON ^
      -D OpenVDB_LIBRARY_DIR=%DEP_ROOT%\archive\extract\2017\openvdb-4.0.2 ^
      -D CMAKE_INSTALL_PREFIX=%VDB_INSTALL% ^
      -D CMAKE_BUILD_TYPE="Release" ^
      -G "Visual Studio 14 2015 Win64" ^
      ..
```

If I don't include HALF_DLL it gets listed as not found in the CMakeCache file. With or without it OpenVDB fails. The only other possibly important things not found are MAYA_glew_LIBRARY and MAYA_glewmx_LIBRARY. I don't believe I'll need to Python debug library.

**Comment by meshula** [comment]
I don't spot any obvious problems with the command line.

I did a clean install of OpenEXR, Half.dll appeared in the correct installation location. I dumped the symbols, and the symbols reported not found in your paste bin are all present. So that eliminates the obvious problems, like OpenEXR not actually publishing it's DLLs or the DLLs not containing symbols.

That points to OpenVdb not linking Half.lib, or finding a bogus copy of Half.lib without the necessary symbols somewhere else on the hard drive.

**Comment by omento** [comment]
I've added the /lib directory of OpenEXR to my system PATH so it shoudn't have any trouble finding it. But for some reason it doesn't and I have to explicitly state the path of the DLL.

In regards to dumping the symbols, would you mind explaining how to do that? When I was building other libraries it would output `.pbd` files, not sure if that would help here. I've attached my CMakeCache if that helps to show where everything is pointing.

[CMakeCache.txt](https://github.com/openexr/openexr/files/1641129/CMakeCache.txt)

**Comment by omento** [comment]
@meshula Would `dumpbin /SYMBOLS` be an appropriate command to run on Half.dll? I don't understand it's output.

```
C:\Code\vfx\openexr\2.2.1\lib>dumpbin /SYMBOLS Half.dll
Microsoft (R) COFF/PE Dumper Version 14.12.25834.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file Half.dll

File Type: DLL

  Summary

        1000 .data
        1000 .gfids
        1000 .pdata
       42000 .rdata
        1000 .reloc
        1000 .rsrc
        2000 .text
```

I've also recompiled IlmBase using the Debug config and ran `cvdump` on Half.pdb

[pdb.txt](https://github.com/openexr/openexr/files/1641595/pdb.txt)

**Comment by omento** [comment]
Left out some info. Running `dumpbin /ALL` on Half.dll output the following file:

[Dumpbin All](https://github.com/openexr/openexr/files/1641652/output.txt)

Here's a snippet that has the two missing symbols in it:

```
  Section contains the following exports for Half.dll

    00000000 characteristics
    5A5E31DC time date stamp Tue Jan 16 12:09:48 2018
        0.00 version
           1 ordinal base
          12 number of functions
          12 number of names

    ordinal hint RVA      name

          1    0 00001240 ??5@YAAEAV?$basic_istream@DU?$char_traits@D@std@@@std@@AEAV01@AEAVhalf@@@Z
          2    1 000012F0 ??6@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@AEAV01@Vhalf@@@Z
          3    2 00043190 ?_eLut@half@@0QBGB
          4    3 00003190 ?_toFloat@half@@0QBTuif@1@B
          5    4 00001320 ?bits@half@@QEBAGXZ
          6    5 00001330 ?convert@half@@CAFH@Z
          7    6 00001410 ?overflow@half@@CAMXZ
          8    7 00001460 ?printBits@@YAXAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@M@Z
          9    8 000014C0 ?printBits@@YAXAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@Vhalf@@@Z
         10    9 00001520 ?printBits@@YAXQEADM@Z
         11    A 00001580 ?printBits@@YAXQEADVhalf@@@Z
         12    B 000015D0 ?setBits@half@@QEAAXG@Z
```

**Comment by meshula** [comment]
Yes, that's what I did. The missing symbols match your pastebin output. eg (_toFloat@half@@0QBTuif@1@B)  That's what made me wonder if Half.lib isn't being linked against openvdb.lib.

Looking at the bottom of your cmakecache, I see this -

openvdb_shared_LIB_DEPENDS:
STATIC=
optimized;C:/Code/vfx/boost/lib64-msvc-14.0/libboost_iostreams-vc140-mt-1_62.lib;
debug;C:/Code/vfx/boost/lib64-msvc-14.0/libboost_iostreams-vc140-mt-gd-1_62.lib;
optimized;C:/Code/vfx/boost/lib64-msvc-14.0/libboost_system-vc140-mt-1_62.lib;
debug;C:/Code/vfx/boost/lib64-msvc-14.0/libboost_system-vc140-mt-gd-1_62.lib;
\general;C:\Program Files\Autodesk\Maya2018\lib\tbb.lib;
general;C:/Code/vfx/openexr/2.2.1/lib/Half.lib;
general;C:\Code\vfx\zlib\1.12.11\lib\zlibstatic.lib;
general;C:/Code/vfx/c-blosc/1.7.0/lib/libblosc.lib;

That's all correct for half.

I did a little digging, and recall that when I last built OpenVdb, I bypassed cmake entirely and handcarved a project file. I found this --- https://github.com/rchoetzlein/win_openvdb --- which suggests that you are not alone in struggling to get the build working. I wonder if his system might work if updated as necessary to reference a modern VisualStudio?

**Comment by kdt3rd** [comment]
fyi, the new cmake (now in master) config-based library information should carry the necessary flags with it to include exr into other projects (i.e. -DOPENEXR_DLL when appropriate). Additionally, if you just link against OpenEXR::IlmImf, that will also link against any libraries that library depends upon.

**Comment by meshula** [comment]
Additionally, the openvdb cmake build has been modernized recently and now includes straight forward build instructions for windows. I'm going to close this, but please reopen if problems still exist.
