### ISSUE TITLE
Out of Memory / Invalid allocation in lmfArray resizeErase (72828572, 72837441)

### ISSUE THREAD

**Issue by Google-Autofuzz** [openexr/openexr#257]
Hello OpenEXR team,

As part of our fuzzing efforts at Google, we have identified an issue affecting
OpenEXR (tested with revision * develop 165dceaeee86e0f8ce1ed1db3e3030c609a49f17).

To reproduce, we are attaching a Dockerfile which compiles the project with
LLVM, taking advantage of the sanitizers that it offers. More information about
how to use the attached Dockerfile can be found here:
https://docs.docker.com/engine/reference/builder/

TL;DR instructions:
* `mkdir project`
* `cp Dockerfile.OpenEXR /path/to/project/Dockerfile`
* `docker build --no-cache /path/to/project`
* `docker run -it image_id_from_docker_build`

From another terminal, outside the container:
`docker cp /path/to/attached/reproducer running_container_hostname:/fuzzing/reproducer`
(reference: https://docs.docker.com/engine/reference/commandline/cp/)

And, back inside the container:
`/fuzzing/repro.sh /fuzzing/reproducer`

Alternatively, and depending on the bug, you could use gcc, valgrind or other
instrumentation tools to aid in the investigation. The sanitizer error that we
encountered is here:

```
==28==WARNING: AddressSanitizer failed to allocate 0xffffffffffffffff bytes
==28==AddressSanitizer's allocator is terminating the process instead of returning 0
==28==If you don't like this behavior set allocator_may_return_null=1
==28==AddressSanitizer CHECK failed: /build/llvm-toolchain-3.9-Qw1aQB/llvm-toolchain-3.9-3.9.1/projects/compiler-rt/lib/sanitizer_common/sanitizer_allocator.cc:199 "((0)) != (0)" (0x0, 0x0)
    #0 0x4db5ff in __asan::AsanCheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) (/fuzzing/openexr_fuzz_tiles+0x4db5ff)
    #1 0x4f5325 in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) (/fuzzing/openexr_fuzz_tiles+0x4f5325)
    #2 0x4e0596 in __sanitizer::ReportAllocatorCannotReturnNull() (/fuzzing/openexr_fuzz_tiles+0x4e0596)
    #3 0x428d0c in __asan::asan_memalign(unsigned long, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType) (/fuzzing/openexr_fuzz_tiles+0x428d0c)
    #4 0x5087d8 in operator new[](unsigned long) (/fuzzing/openexr_fuzz_tiles+0x5087d8)
    #5 0x7f41c23d3557 in Imf_2_2::Array<char>::resizeErase(long) /fuzzing/openexr/OpenEXR/IlmImf/./ImfArray.h:196:14
    #6 0x7f41c23d3042 in Imf_2_2::OpaqueAttribute::readValueFrom(Imf_2_2::IStream&, int, int) /fuzzing/openexr/OpenEXR/IlmImf/ImfOpaqueAttribute.cpp:100:11
    #7 0x7f41c23b820b in Imf_2_2::Header::readFrom(Imf_2_2::IStream&, int&) /fuzzing/openexr/OpenEXR/IlmImf/ImfHeader.cpp:1219:9
    #8 0x7f41c24de3d6 in Imf_2_2::MultiPartInputFile::initialize() /fuzzing/openexr/OpenEXR/IlmImf/ImfMultiPartInputFile.cpp:316:16
    #9 0x7f41c24df0e0 in Imf_2_2::MultiPartInputFile::MultiPartInputFile(Imf_2_2::IStream&, int, bool) /fuzzing/openexr/OpenEXR/IlmImf/ImfMultiPartInputFile.cpp:161:9
    #10 0x7f41c2481cbc in Imf_2_2::TiledInputFile::compatibilityInitialize(Imf_2_2::IStream&) /fuzzing/openexr/OpenEXR/IlmImf/ImfTiledInputFile.cpp:862:32
    #11 0x7f41c24813d1 in Imf_2_2::TiledInputFile::TiledInputFile(char const*, int) /fuzzing/openexr/OpenEXR/IlmImf/ImfTiledInputFile.cpp:714:6
    #12 0x7f41c24b0efa in Imf_2_2::TiledRgbaInputFile::TiledRgbaInputFile(char const*, int) /fuzzing/openexr/OpenEXR/IlmImf/ImfTiledRgbaFile.cpp:773:21
    #13 0x50bada in fuzzImage(char const*) /fuzzing/security-research-pocs/autofuzz/openexr_fuzz_tiles.cc:135:14
    #14 0x50b9c5 in LLVMFuzzerTestOneInput /fuzzing/security-research-pocs/autofuzz/openexr_fuzz_tiles.cc:178:3
    #15 0x514d3c in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/fuzzing/openexr_fuzz_tiles+0x514d3c)
    #16 0x5144fe in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long) (/fuzzing/openexr_fuzz_tiles+0x5144fe)
    #17 0x50e36d in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*) (/fuzzing/openexr_fuzz_tiles+0x50e36d)
    #18 0x50f83f in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/fuzzing/openexr_fuzz_tiles+0x50f83f)
    #19 0x50e21c in main (/fuzzing/openexr_fuzz_tiles+0x50e21c)
    #20 0x7f41c0fbf2b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)
    #21 0x4210e9 in _start (/fuzzing/openexr_fuzz_tiles+0x4210e9)
```

One immediate suggestion is to ensure that APIs such as resizeErase and
resizeEraseUnsafe reject negative values and propagate an error status back to
callers (or if this is only used internally, modifying all call sites to perform
similar checks).

We will gladly work with you so you can successfully confirm and reproduce this
issue. Do let us know if you have any feedback surrounding the documentation.

Once you have reproduced the issue, we'd appreciate to learn your expected
timeline for an update to be released. With any fix, please attribute the report
to "Google Autofuzz project".

We are also pleased to inform you that your project is eligible for inclusion to
the OSS-Fuzz project, which can provide additional continuous fuzzing, and
encourage you to investigate integration options.

Don't hesitate to let us know if you have any questions!

Google AutoFuzz Team
[artifacts_72828572.zip](https://github.com/openexr/openexr/files/1704500/artifacts_72828572.zip)

**Comment by peterhillman** [comment]
Duplicate of #248, and now fixed in PR #436
