### ISSUE TITLE
Signed Integer Overflow in getTiledChunkOffsetTableSize (72377177)

### ISSUE THREAD

**Issue by Google-Autofuzz** [openexr/openexr#265]
Hello OpenEXR team,

As part of our fuzzing efforts at Google, we have identified an issue affecting
OpenEXR (tested with revision develop 165dceaeee86e0f8ce1ed1db3e3030c609a49f17).

To reproduce, we are attaching a Dockerfile which compiles the project with
LLVM, taking advantage of the sanitizers that it offers. More information about
how to use the attached Dockerfile can be found here:
https://docs.docker.com/engine/reference/builder/

TL;DR instructions:
* `mkdir project`
* `cp Dockerfile /path/to/project`
* `docker build --no-cache /path/to/project`
* `docker run -it image_id_from_docker_build`

From another terminal, outside the container:
`docker cp /path/to/attached/reproducer running_container_hostname:/fuzzing/reproducer`
(reference: https://docs.docker.com/engine/reference/commandline/cp/)

And, back inside the container:
`/fuzzing/repro.sh /fuzzing/reproducer`

Alternatively, and depending on the bug, you could use gcc, valgrind or other
instrumentation tools to aid in the investigation. The sanitizer error that we
encountered is here:

ImfTiledMisc.cpp:371:48: runtime error: signed integer overflow: 419431 * 838864 cannot be represented in type 'int'
SUMMARY: AddressSanitizer: undefined-behavior ImfTiledMisc.cpp:371:48 in 

We will gladly work with you so you can successfully confirm and reproduce this
issue. Do let us know if you have any feedback surrounding the documentation.

A possible fix for this issue has been attached for your consideration.

Once you have reproduced the issue, we'd appreciate to learn your expected
timeline for an update to be released. With any fix, please attribute the report
to "Google Autofuzz project".

We are also pleased to inform you that your project is eligible for inclusion to
the OSS-Fuzz project, which can provide additional continuous fuzzing, and
encourage you to investigate integration options.

Don't hesitate to let us know if you have any questions!

Google AutoFuzz Team
[72377177.txt](https://github.com/openexr/openexr/files/1721674/72377177.txt)
[artifacts_72377177.txt](https://github.com/openexr/openexr/files/1721675/artifacts_72377177.txt)

**Comment by Google-Autofuzz** [comment]
Additional patch that fixes the signed int overflow in the addition to lineOffsetSize.

Please apple both this patch (73783931.txt) and the path attached in #1 (72377177.txt).
[73783931.txt](https://github.com/openexr/openexr/files/1753385/73783931.txt)

**Comment by peterhillman** [comment]
Fixed by enforcing a limit to maximum number of tiles
