### ISSUE TITLE
Cmake installation of ilmbase places .dll files under `/lib` instead of `/bin`

### ISSUE THREAD

**Issue by SylvainCorlay** [openexr/openexr#274]
On windows platforms, `.dll` files should be installed under `PREFIX\bin` and the import libraries `.lib` should be installed under `PREFIX\lib`.

**Comment by SylvainCorlay** [comment]
I came upon this issue as I was working on the packaging of `openexr` for the conda package manager.

**Comment by meshula** [comment]
Hi, this commit on the develop branch should fix the issue.

https://github.com/openexr/openexr/commit/9f23bcc60b9786ffd5d97800750b953313080c87

**Comment by cary-ilm** [comment]
Looking into the OpenEXR project backlog... Closing this issue, as it seems to be resolved.
