### ISSUE TITLE
IlmBase math tests fail

### ISSUE THREAD

**Issue by TheOtherDave** [openexr/openexr#277]
Hi, everyone.

I'm trying to build OpenEXR 2.2.1 with ICC/ICPC 18.0.1, on a system with two Xeon E5-2699 CPUs, running CentOS 7.4, and am having trouble with ImathTest.

The relevant env vars are (at least I think those are the relevant ones):
> CC=icc
> CXX=icpc
> CFLAGS="-g -fPIC -xHost -O2 -std=c11"
> CXXFLAGS="-g -fPIC -xHost -O2 -std=c++14"

The build commands are:
> ./bootstrap
> ./configure --prefix=/usr/local
> make -j
> make -j check
> make install

Here's a list of the failed assertions, and what I did to fix them:
> testInvert.cpp:65: void <unnamed>::invertM44f(const Imath_2_2::Matrix44<float> &, float): Assertion `ident1.equalWithAbsError (identity44f, e)' failed.

Changed lines 119-121 and 149-151 to pass 1e-6 as their last parameter instead of 0

> testBoxAlgo.cpp:908: void <unnamed>::boxMatrixTransform(): Assertion `b51 == b5' failed.

Commented-out line 908 (because I didn't see an "approximately equals" function for Box types)

> testTinySVD.cpp:110: void verifyTinySVD_3x3(const Imath_2_2::Matrix33<T> &) [with T = float]: Assertion `std::abs (product[i][j] - A[i][j]) <= valueEps' failed.

Changed 'valueEps' to '(2 * valueEps)'

Do these solutions seem reasonable? Does anybody know what's causing the problems in the first place?

**Comment by cary-ilm** [comment]
Looking into the OpenEXR backlog.

We definitely don't want to change the comparison threshold. Something else is going on. Are you still getting these errors? Any more information you can provide?

**Comment by cary-ilm** [comment]
Closing the issue for now, feel free to re-open or file a new issue if you need further help.
