### ISSUE TITLE
IlmBase should link pthread

### ISSUE THREAD

**Issue by moben** [openexr/openexr#282]
Otherwise openexr will fail to build if IlmBase was built with `--as-needed`.

Arch and Fedora Linux (and probably others) carry this patch to fix the issue:
https://git.archlinux.org/svntogit/packages.git/plain/trunk/ilmbase-2.0.1-no_undefined.patch?h=packages/ilmbase

**Comment by kdt3rd** [comment]
Using the new cmake build infrastructure merged to master, ldd libIlmThread-2_3.so shows it loading libpthread, PR #446 will fix this for autoconf / configure users
