### ISSUE TITLE
Error when linking Half project: unresolved external symbol "private: static union half::uif const * const half::_toFloat" (?_toFloat@half@@0QBTuif@1@B)

### ISSUE THREAD

**Issue by ghost** [openexr/openexr#302]
This error happens when I am building OpenVDB 5.1.0's `openvdb_shared` project which links to `Half-2_2.lib`. The building environment is:
- Windows 10 version 1803
- Visual Studio 2015 Update 3
- dev branch of IlmBase downloaded from here
- OpenVDB and IlmBase are both built under Debug x64 DLL mode in VS

The full error messages are:
```
 1>------ Build started: Project: openvdb_shared, Configuration: Debug x64 ------
 1>     Creating library C:/.../openvdb-5.1.0/build/openvdb/Debug/openvdb.lib and object C:/.../openvdb-5.1.0/build/openvdb/Debug/openvdb.exp
 1>points.obj : error LNK2001: unresolved external symbol "private: static union half::uif const * const half::_toFloat" (?_toFloat@half@@0QBTuif@1@B)
 1>openvdb.obj : error LNK2001: unresolved external symbol "private: static union half::uif const * const half::_toFloat" (?_toFloat@half@@0QBTuif@1@B)
 1>points.obj : error LNK2001: unresolved external symbol "private: static unsigned short const * const half::_eLut" (?_eLut@half@@0QBGB)
 1>openvdb.obj : error LNK2001: unresolved external symbol "private: static unsigned short const * const half::_eLut" (?_eLut@half@@0QBGB)
 1>C:\...\openvdb-5.1.0\build\openvdb\Debug\openvdb.dll : fatal error LNK1120: 2 unresolved externals
 ========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========
```
`_toFloat` and `_eLut` are defined in line 56-59 in `half.cpp` of IlmBase as follows:
```
HALF_EXPORT const half::uif half::_toFloat[1 << 16] =
    #include "toFloat.h"
HALF_EXPORT const unsigned short half::_eLut[1 << 9] =
    #include "eLut.h"
```
where  `HALF_EXPORT` is defined as `__declspec(dllexport)` (Visual Studio can grey out inactive code so I am sure that's the correct definition. The hints popped up in VS also confirmed that). A clue is that the second HALF_EXPORT is underlined with red which says "Initialization with '{...}' expected for aggregate object".

I checked Half-2_2.lib using dumpbin and found that _toFloat and _eLut are listed as two of 25 public symbols:
>       D08 Half-2_2_NULL_THUNK_DATA
>      1022 __imp_?_toFloat@half@@0QBTuif@1@B
>       FB2 __imp_?_eLut@half@@0QBGB
>      109C ?bits@half@@QEBAGXZ
I'm curious why they are prefixed with __imp.

A similar thread is here: https://github.com/alembic/alembic/issues/40. The first error therein is exactly what I encountered. The thread there is responded with a question:

> 1. do the platform defines for DLL_EXPORT match between Alembic on OpenEXR?

I don't quite understand what this question is asking about. So could you please continue to solve this problem? I won't keep silent at your inquiry. Please let me know what info you need to troubleshoot this problem; I will answer as soon as I can. Thank you.

**Comment by meshula** [comment]
What the alembic#40 issue is saying is that OPENEXR_DLL needs to be set in the preprocessor definitions whilst building OpenVdb. This should be set in the OpenVdb cmake files.

OpenVdb/PlatformConfig.h attempts to set this correctly.

Perhaps the place to start is to discover at line 54 in that file, whether OPENEXR_DLL is set or not. It should be set.

**Comment by zhou-heng** [comment]
Thank you. The related lines in openvdb\PlatformConfig.h are:
```
    // By default, assume that we're dynamically linking OpenEXR, unless
    // OPENVDB_OPENEXR_STATICLIB is defined.
    #if !defined(OPENVDB_OPENEXR_STATICLIB) && !defined(OPENEXR_DLL)
		#define OPENEXR_DLL
    #endif
```
So `OPENEXR_DLL` is correctly defined in my openvdb_shared project. IlmBase were built with Debug x64 DLL mode too and there is no pre/post-built event or custom build steps in all VS projects involved. For your reference, these are preprocessors of the openvdb_shared project:
> WIN32
> _WINDOWS
> OPENVDB_ABI_VERSION_NUMBER=5
> BOOST_ALL_NO_LIB
> _WIN32
> NOMINMAX
> HALF_EXPORTS
> OPENVDB_DLL
> CMAKE_INTDIR="Debug"
> openvdb_shared_EXPORTS
>
and these are libraries to be linked to openvdb_shared project in addition to system libraries which are all built as DEBUG x64 DLL:
> C:\local\boost_1_67_0\lib64-msvc-14.0\boost_iostreams-vc140-mt-gd-x64-1_67.lib
> C:\local\boost_1_67_0\lib64-msvc-14.0\boost_system-vc140-mt-gd-x64-1_67.lib
> C:\...\tbb2018_20180618oss\lib\intel64\vc14\tbb_debug.lib
> C:\...\openexr-develop\IlmBase\install_\lib\Half-2_2.lib
> C:\...\zlib-1.2.11\install\lib\zlib.lib
> C:\...\c-blosc-master\install\lib\blosc.lib
>
Now what?

**Comment by zhou-heng** [comment]
The problem is magically solved by removing HALF_EXPORTS from preprocessor definitions in VS. So what on earth is this macro for? How to let CMake not to define it in its command line when setting up VS2015 solution?

**Comment by meshula** [comment]
HALF_EXPORTS should only be set by Cmake for the Half project itself in order to cause symbols to export. It is done  in openexr/IlmBase/Half/Cmakelists.txt.  The definition is marked private,
```
  TARGET_COMPILE_DEFINITIONS ( Half PRIVATE HALF_EXPORTS )
```
so it should not be leaking out from the OpenEXR Cmake files into OpenVdb.

I am trying to imagine how that symbol could have leaked. Is it possible that openexr cmake cache files were still on your drive when you switched to using the dev branch?

**Comment by zhou-heng** [comment]
The old OpenEXR has all been deleted, so only dev branch of openexr are on my hard drive. Also, I repeated building of OpenEXR & IlmBase and OpenVDB (using its github version which is 5.2) in a brand new separate folder, so there should be no cache residues affecting building, but the HALF_EXPORTS still shows up in various projects of OpenVDB VS solution like openvdb_shared and openvdb_static. 

There is another famous project that uses OpenEXR & IlmBase: OpenImageIO. If IlmBase leaks, HALF_EXPORTS should appear in the OIIO project. But there is no HALF_EXPORTS in OIIO. So I think it should be OpenVDB's problem. Should I submit an issue to OpenVDB's github?

**Comment by meshula** [comment]
Yes, and please reference the issue here so we can follow the progress.

**Comment by kdt3rd** [comment]
fyi, with the new "modern cmake" re-write of our install process, the cmake config file thing should fully separate private #defines and public #defines such as this. It would be good to confirm this is working as intended under windows prior to our pending release.

**Comment by meshula** [comment]
I checked. OPENEXR_DLL propagates as expected. HALF_EXPORTS (and all other *_EXPORTS) macros do not propagate. If anyone observes differently, please reopen the issue.

**Comment by danrbailey** [comment]
Mentioning that this issue was also reported in the vdb_render binary recently, where I believe the issue was also not correctly defining OPENEXR_DLL. The master branch of OpenVDB and OpenEXR 2.3 currently exhibit this issue and I've put in a PR to address this here:

https://github.com/AcademySoftwareFoundation/openvdb/pull/550
