### ISSUE TITLE
min/max name conflict

### ISSUE THREAD

**Issue by zhou-heng** [openexr/openexr#304]
My environment:
 - Windows
 - Visual Studio 

I had not planned to speak out on this but finally couldn't help.

In `ImathHalfLimits.h`, symbols `min`/`max` is specifically defined as follows:
```
    static float		min()		{return -HALF_MAX;}
    static float		max()		{return HALF_MAX;}
```
But unfortunately, `std` also have these name defined. To resolve name conflict, we all know C++ introduced the mechanism of namespace. so we can refer to these names in `std` as `std::min` or `std::max`. But unfortunately again, IlmBase\Half\half.cpp writes in line 50:

`using namespace std;`

So `min` in the definition of `struct limits <half>` in ImathHalfLimits.h is understood by VS as a call to `std::min`, which causes a sequence of errors like below if OpenEXR is build along with other 3rd party opensource like Field3D.
```
1>C:\...\openexr-develop\IlmBase\install_\include\OpenEXR/ImathHalfLimits.h(58): warning C4003: not enough actual parameters for macro 'min'
1>C:\...\openexr-develop\IlmBase\install_\include\OpenEXR/ImathHalfLimits.h(59): warning C4003: not enough actual parameters for macro 'max'
1>C:\...\openexr-develop\IlmBase\install_\include\OpenEXR/ImathHalfLimits.h(58): error C2059: syntax error: ')'
1>C:\...\openexr-develop\IlmBase\install_\include\OpenEXR/ImathHalfLimits.h(58): error C2334: unexpected token(s) preceding ':'; skipping apparent function body
1>C:\...\openexr-develop\IlmBase\install_\include\OpenEXR/ImathHalfLimits.h(64): error C2143: syntax error: missing ')' before ';'
1>C:\...\openexr-develop\IlmBase\install_\include\OpenEXR/ImathHalfLimits.h(64): error C2059: syntax error: ')'
1>C:\...\openexr-develop\IlmBase\install_\include\OpenEXR/ImathHalfLimits.h(64): error C2238: unexpected token(s) preceding ';'
```
The statement `using namespace std;` should only be used in homework or small course project in universities; professional developers in industry of large projects like OpenEXR should always explicitly write down `std::` because it often happens that a name you like has already been taken in `std`. This is a principle in industry, so far as I know. C++ standard won't change its names because of you, so you should not be lazy and should take care accordingly.

But this happens in OpenEXR. Although I work around this issue by
```
#undef min
#undef max
```
before the specialization of `struct limits <half>`, this way the user of OpenEXR would never be able to use min/max as s/he might expects. Imagine how frustrating a student in university might be who likes to `using namespace std;` in his/her C++ code and who are learning to use openEXR in a small project. The tons of errors would soon overwhelm him/her.

Although I build OpenEXR on Windows, `std::min/max` is standard C++ function. The problem in this thread has nothing to do with Windows, and I am curious how Field3D guys make it on Linux (I made quite a few modifications to port it to Windows).

So I hope OpenEXR could remove `using namespace std;` from the source and add `std::` whenever needed. It looks like a lot of work but is worth its while, if you think OpenEXR is a profession software. Thank you.

**Comment by KevinJW** [comment]
Those functions you quote from ImathHalfLimits.h are just that, they are member functions of the struct limits inside the namespace defined by IMATH_INTERNAL_NAMESPACE.

Your problem is with macros defined somewhere in your translation unit, this is confirmed by your ability to #undef them. As your environment is Visual Studio under Windows then likely you need to either:

- Pass /D NOMINMAX to your compiler invocation flags 

or

- #define NOMINMAX
 prior to including any Windows specific header files but specifically Windows.h

As to the "using namespace std" inside the .cpp file you mention, this is not normally considered bad form stylistically, as traditionally you do not routinely #include .cpp files inside other parts of your translation unit. If this occurred inside a public header file I would agree with you.

Kevin

**Comment by zhou-heng** [comment]
Thank you for sharing the idea with me.
This ticket can be closed now.
