### ISSUE TITLE
recommended boost version?

### ISSUE THREAD

**Issue by ssteinbach** [openexr/openexr#41]
Hi Guys,

I was wondering, is there a recommended version of boost for building the PyImath bindings?  I'm trying to compile against boost 1.51.0 on mac os x (mountain lion).  This is compiling on revision 2664764a113839d79e48616f40a3c60c595537a7.

I'm seeing lots of build errors and assuming it has something to do with incompatible boost versions, but  am not sure.

(pages like this):
/opt/local/include/boost/python/operators.hpp: In static member function 'static PyObject\* boost::python::detail::operator_l<op_add>::apply<L, R>::execute(typename boost::python::detail::unwrap_wrapper_<L>::type&, const typename boost::python::detail::unwrap_wrapper_<R>::type&) [with L = PyImath::FixedArray2D<int>, R = PyImath::FixedArray2D<int>]':
/opt/local/include/boost/python/operators.hpp:152:   instantiated from 'void boost::python::detail::operator_<id, L, R>::visit(ClassT&) const [with ClassT = boost::python::class_PyImath::FixedArray2D<int, boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified>, boost::python::detail::operator_id id = op_add, L = boost::python::self_ns::self_t, R = boost::python::self_ns::self_t]'
/opt/local/include/boost/python/def_visitor.hpp:31:   instantiated from 'static void boost::python::def_visitor_access::visit(const V&, classT&) [with V = boost::python::def_visitor<boost::python::detail::operator_<op_add, boost::python::self_ns::self_t, boost::python::self_ns::self_t> >, classT = boost::python::class_PyImath::FixedArray2D<int, boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified>]'
/opt/local/include/boost/python/def_visitor.hpp:67:   instantiated from 'void boost::python::def_visitor<DerivedVisitor>::visit(classT&) const [with classT = boost::python::class_PyImath::FixedArray2D<int, boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified>, DerivedVisitor = boost::python::detail::operator_<op_add, boost::python::self_ns::self_t, boost::python::self_ns::self_t>]'
/opt/local/include/boost/python/class.hpp:226:   instantiated from 'boost::python::class_<T, X1, X2, X3>& boost::python::class_<T, X1, X2, X3>::def(const boost::python::def_visitor<Derived>&) [with Derived = boost::python::detail::operator_<op_add, boost::python::self_ns::self_t, boost::python::self_ns::self_t>, W = PyImath::FixedArray2D<int>, X1 = boost::python::detail::not_specified, X2 = boost::python::detail::not_specified, X3 = boost::python::detail::not_specified]'
./PyImathFixedArray2D.h:651:   instantiated from 'void PyImath::add_arithmetic_math_functions(boost::python::class_PyImath::FixedArray2D<T, boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified>&) [with T = int]'
imathmodule.cpp:175:   instantiated from here
/opt/local/include/boost/python/operators.hpp:212: error: no match for 'operator+' in 'l + r'

I may have missed it in the docs, sorry about that!

**Comment by meshula** [comment]
Does a modern boost work now?

**Comment by Arturo-gutierrez** [comment]
soooo.... does it work yet?
