### ISSUE TITLE
Recommended way of opening an EXR file in python?

### ISSUE THREAD

**Issue by ssteinbach** [openexr/openexr#50]
Is there a python wrapper for opening an EXR file and getting imath values back of pixels?

**Comment by mguillau** [comment]
This is a very late reply, but these python bindings have been working well for me:
http://excamera.com/sphinx/articles-openexr.html

**Comment by KelSolaar** [comment]
https://github.com/OpenImageIO/oiio has Python bindings and can read and write EXR images.

**Comment by cary-ilm** [comment]
Looking into the OpenEXR issue backlog. Closing this issue, based on the previous comments.
