### ISSUE TITLE
testBox failure on i386

### ISSUE THREAD

**Issue by quantizationbit** [openexr/openexr#67]
System Slackware 14.0, 32 bit, gcc 4.7.1

Compiles but "make check" fails into the testing of ImathTest. I'm trying to put together a full clean build/install of OpenEXR, CTL (1.5 rc) to utilize ultimately ctlrender command for some testing. I've removed prior builds and removed openexr 1.7.0 package which comes with Slackware by default.

lt-ImathTest: testBox.cpp:253: void {anonymous}::testExtendByPoint(const char*) [with T = Imath_2_0::Vec2<double>]: Assertion `b.min == p && b.max == p' failed.
/bin/sh: line 5:  8024 Aborted                 ${dir}$tst
# FAIL: ImathTest
#1 of 1 test failed

make[2]: **\* [check-TESTS] Error 1
make[2]: Leaving directory `/home/qbit/Documents/OpenEXR/openexr-2.0.1/IlmBase/ImathTest'
make[1]: *** [check-am] Error 2
make[1]: Leaving directory`/home/qbit/Documents/OpenEXR/openexr-2.0.1/IlmBase/ImathTest'
make: **\* [check-recursive] Error 1
qbit@0xFFFB:~/Documents/OpenEXR/openexr-2.0.1/IlmBase$ 

Thanks,
Bill Mandel

**Comment by cary-ilm** [comment]
Looking into the OpenEXR issue backlog.  Is this still an issue, or ok to close?

**Comment by cary-ilm** [comment]
Closing the issue for now, feel free to re-open or file a new issue if you need further help.
