### ISSUE TITLE
compile openexr with mingw 64 bit

### ISSUE THREAD

**Issue by jb-alvarado** [openexr/openexr#79]
I can compile the complete source with mingw 32 bit under windows, but with the 64 bit version I get some errors. For the compiling I use this commands:
https://github.com/jb-alvarado/media-autobuild_suite/blob/master/wip%28temp%29/compile_imagemagick64.sh#L173-L227

First I was getting the error about:
ImfSystemSpecific.h:64: error: 'posix_memalign' was not declared in this scope

I fix that with this lines in ImfSystemSpecific.h:
# define _aligned_malloc __mingw_aligned_malloc
# define _aligned_free  __mingw_aligned_free

static void\* EXRAllocAligned(size_t size, size_t alignment)
{
    return _aligned_malloc(alignment, size);
}

static void EXRFreeAligned(void\* ptr)
{
    _aligned_free(ptr);
}

But now I get this error:

/bin/sh ../libtool --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../config -ID:/_System/mingw/local64/include/OpenEXR -I.. -I../config  -I/local64/include -pipe -I/local64/include -mms-bitfields -mthreads -MT ImfDeepScanLineOutputFile.lo -MD -MP -MF .deps/ImfDeepScanLineOutputFile.Tpo -c -o ImfDeepScanLineOutputFile.lo ImfDeepScanLineOutputFile.cpp
In file included from ImfScanLineInputFile.cpp:61:0:
ImfOptimizedPixelReading.h: In function 'bool Imf_2_0::isPointerSSEAligned(const void_)':
ImfOptimizedPixelReading.h:264:50: error: cast from 'const void_ __restrict__' to 'long unsigned int' loses precision [-fpermissive]
     unsigned long trailingBits = ((unsigned long)pPointer) & 15;

Is there any chance to fix that?

**Comment by cary-ilm** [comment]
Looking into the OpenEXR issue backlog. It seems this issue has been address, as described in #80. Reopen or file another issue if that's not the case.
