### ISSUE TITLE
testFutureProofing and testMultiPartFileMixingBasic fail on big endian arches

### ISSUE THREAD

**Issue by sharkcz** [openexr/openexr#81]
testFutureProofing and testMultiPartFileMixingBasic both use fread(&length,4,f) to get a 4 byte integer value from input file. The value read is not converted from the little endian format to the machine format causing problems (eg. test didn't finish after 24 hours).

something like 

<pre>
+#include "byteswap.h"
+#include "ImfSystemSpecific.h"

...
             fread(&length,4,1,f);
+            if (!GLOBAL_SYSTEM_LITTLE_ENDIAN)
+            {
+                int tmp = bswap_32(length);
+               length = tmp;
+            }

...
</pre>

should be used

**Comment by malaterre** [comment]
Link was broken for me. It should read: http://pkgs.fedoraproject.org/cgit/OpenEXR.git/tree/openexr-2.1.0-bigendian.patch

**Comment by kloczek** [comment]
Please submit this patch as PR.

**Comment by cary-ilm** [comment]
This seems to have been resolved.  Closing the issue for now, feel free to re-open or file a new issue if you need further help.
