### ISSUE TITLE
VS 2010 broken: exporting std::string subclass crashes

### ISSUE THREAD

**Issue by sebastianelsner** [openexr/openexr#86]
The issue was already discussed on the mailing list, this is just for the sake of completion:

nick.porcino@gmail.com
Right, on windows one can't derive from standard string and then export the
class. When the exception is thrown, Iex will crash deep in heap code in
the Stdlib.

halfdan@sidefx.com
The problem is that BaseExc derives from std::string, which doesn't have a dllexport in MSVC2010 and onwards, and so in our case, actually broke the build.
We patched our version so that BaseExc uses std::string as a member variable, rather than deriving from it. This was easy enough to do, since this change only affects testBaseExc.cpp.

**Comment by cary-ilm** [comment]
Looking into the OpenEXR issue backlog. This appears to have been addressed in v2.3.0
