### ISSUE TITLE
MultiPartOutputFile API fails when single part has no type

### ISSUE THREAD

**Issue by peterhillman** [openexr/openexr#92]
Either the API should inject 'SCANLINEIMAGE' type, or presence of type should be checked even in single part files

**Comment by cary-ilm** [comment]
@peterhillman is still still an issue worth considering?

**Comment by peterhillman** [comment]
I'll close this. Trying to create a multipart output file now checks that every part has a 'type' attribute even if only one part is written to the file, which is consistent behaviour for the using the MultiPartOutputFile class
