### ISSUE TITLE
Race condition in creation of LockedTypeMap and registerAttributeTypes 

### ISSUE THREAD

**Issue by mikearmstrong001** [openexr/openexr#98]
Mutex will only be initialized on first call, suggestion is to move the static Mutex outside of the function.

Mike

---

IlmImf/ImfAttribute.cpp

LockedTypeMap &
typeMap ()
{
    // race condition
    static Mutex criticalSection;
    // end race condition
    Lock lock (criticalSection);

```
static LockedTypeMap* typeMap = 0;

if (typeMap == 0)
typeMap = new LockedTypeMap ();

return *typeMap;
```

}

OpenEXR/IlmImf/ImfHeader.cpp

void
staticInitialize ()
{
    // race condition
    static Mutex criticalSection;
    // end race condition
    Lock lock (criticalSection);

```
static bool initialized = false;

if (!initialized)
{
```

**Comment by cary-ilm** [comment]
Looking into the OpenEXR backlog.

This issues appears to be fixed by 00df2c72ca1b7cb148e19a9bdc44651a6c74c9e4 in release v.2.3.0.
